const mongoose = require('mongoose')
const modelName = require('../config/modelname').oil
var d = new Date();
const TwoTankOilStorage= new mongoose.Schema({
    check1:{
        type:Boolean,
        default:false
     },
     check2:{
        type:Boolean,
        default:false
     }
})
const InspectionCheckList= new mongoose.Schema({
    check1:{
        type:Boolean,
        default:false
    },
    check2:{
        type:Boolean,
        default:false
     },
     check3:{
        type:Boolean,
        default:false
     },
     check4:{
        type:Boolean,
        default:false
     },
     check5:{
        type:Boolean,
        default:false
     },
     check6:{
        type:Boolean,
        default:false
    },
    check7:{
        type:Boolean,
        default:false
     },
     check8:{
        type:Boolean,
        default:false
     },
     check9:{
        type:Boolean,
        default:false
     }
})
const TankLocation = new mongoose.Schema({
    indoor:{
        type:Boolean,
        default:false
    },
    outdoor:{
        type:Boolean,
        default:false
    }
})
const ReasonForInspection= new mongoose.Schema({
    newInstallation:{
        type:Boolean,
        default:false
    },
    serviceMaintenance:{
        type:Boolean,
        default:false
    },
    newCustomer:{
        type:Boolean,
        default:false
    },
    insuranceRequirement:{
        type:Boolean,
        default:false
    }
})

const capacityDrop = new mongoose.Schema({
    "id":{
        type:String
    },
    "value":{
        type:String
    }
})
const currentLevelDrop = new mongoose.Schema({
    "id":{
        type:String
    },
    "value":{
        type:String
    }
})
const manuf1Drop = new mongoose.Schema({
    "id":{
        type:String
    },
    "value":{
        type:String
    }
})
const modelNo1Drop = new mongoose.Schema({
    "id":{
        type:String
    },
    "value":{
        type:String
    }
})
const serialNo1Drop = new mongoose.Schema({
    "id":{
        type:String
    },
    "value":{
        type:String
    }
})
const OilStorageDetails = new mongoose.Schema({
    manuf:manuf1Drop,
    modelNo:modelNo1Drop,
    serialNo:serialNo1Drop,
    year:{
        type:String
    },
    capacity:capacityDrop,
    currentLevel:currentLevelDrop,
    ReasonForInspection:ReasonForInspection,
    TankLocation:TankLocation,
    InspectionCheckList:InspectionCheckList,
    TwoTankOilStorage:TwoTankOilStorage
})


const maintainanceCheckList = new mongoose.Schema({
    check1:{
        type:Boolean,
        default:false
    },
    check2:{
        type:Boolean,
        default:false
    },
    check3:{
        type:Boolean,
        default:false
    },
    check4:{
        type:Boolean,
        default:false
    },
    check5:{
        type:Boolean,
        default:false
    },
    check6:{
        type:Boolean,
        default:false
    },
    check7:{
        type:Boolean,
        default:false
    },
    check8:{
        type:Boolean,
        default:false
    },
    check9:{
        type:Boolean,
        default:false
    },
    check10:{
        type:Boolean,
        default:false
    },
    check11:{
        type:Boolean,
        default:false
    },
    check12:{
        type:Boolean,
        default:false
    },
    check13:{
        type:Boolean,
        default:false
    },
    check14:{
        type:Boolean,
        default:false
    },
    check15:{
        type:Boolean,
        default:false
    },
    check16:{
        type:Boolean,
        default:false
    },
    check17:{
        type:Boolean,
        default:false
    }
})
const oilFilter  = new mongoose.Schema({
    ['1A30']:{
        type:Boolean,
        default:false
    },
    ['NG3500']:{
        type:Boolean,
        default:false
    },
    ['K10']:{
        type:Boolean,
        default:false
    },
    check1:{
        type:Boolean,
        default:false
    },
    check2:{
        type:Boolean,
        default:false
    },
    check3:{
        type:Boolean,
        default:false
    },
    check4:{
        type:Boolean,
        default:false
    },
    check5:{
        type:Boolean,
        default:false
    },
    check6:{
        type:Boolean,
        default:false
    },
    check7:{
        type:Boolean,
        default:false
    },
    check8:{
        type:Boolean,
        default:false
    }
})
const combustionAnalysis = new mongoose.Schema({
    Temp:{
        type:Boolean,
        default:false
    },
    ['CO2']:{
        type:Boolean,
        default:false
    },
    ['02']:{
        type:Boolean,
        default:false
    },
    ExAir:{
        type:Boolean,
        default:false
    },
    Effic:{
        type:Boolean,
        default:false
    },
    Draft:{
        type:Boolean,
        default:false
    },
    CO:{
        type:Boolean,
        default:false
    },
    Smoke:{
        type:Boolean,
        default:false
    }
})
const applncTypeDrop = new mongoose.Schema({
    "id":{
        type:String
    },
    "value":{
        type:String
    }
})
const manufDrop = new mongoose.Schema({
    "id":{
        type:String
    },
    "value":{
        type:String
    }
})
const modelNoDrop = new mongoose.Schema({
    "id":{
        type:String
    },
    "value":{
        type:String
    }
})
const serialNoDrop = new mongoose.Schema({
    "id":{
        type:String
    },
    "value":{
        type:String
    }
})
const nozzleDrop = new mongoose.Schema({
    "id":{
        type:String
    },
    "value":{
        type:String
    }
})
const airFilterSizeDrop = new mongoose.Schema({
    "id":{
        type:String
    },
    "value":{
        type:String
    }
})
const oilAppDtls = new mongoose.Schema({
    applncType:applncTypeDrop,  
    manuf:manufDrop,
    modelNo:modelNoDrop,
    serialNo:serialNoDrop,
    nozzle:nozzleDrop,
    airFilterSize:airFilterSizeDrop,
    combustionAnalysis:combustionAnalysis,
    oilFilter:oilFilter,
    maintainanceCheckList:maintainanceCheckList
})
const customerReview = new mongoose.Schema({
    rating:{
        type:Number,
        default:3
    },
    comment:{
        type:String
    }
})

const OilSchema = new mongoose.Schema({
    accNo:{
        type:String,
        required:true
    },
    workOrderId:{
        type:String,
        default:""
    },
    date:{
        type:String,
        default:d.getDate()+'-'+d.getMonth()+1+'-'+d.getFullYear()
    },
    empId:{
        type:String,
        required:true
    },
    status:{
        type:String
    },
    createdBy:{
        type:String
    },
    oilAppDtls:oilAppDtls,
    Notes:{
        type:String,
    },
    techName:{
        type:String
    },
    signature:{
        type:String
    },
    certNo:{
        type:String
    },
    customer:customerReview,
    priority:{
        type:String
    },
    comment:{
        type:String
    },
    imageBinary:{
        type:String,
        default:""
    },
    OilStorageDetails:OilStorageDetails,
    notifSent:{
        type:Number,
        default:0
    }
})


global[modelName] = mongoose.model(modelName,OilSchema);

module.exports = global[modelName]
