// LOGIN ACTIONS
export let LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export let LOGIN_PENDING = 'LOGIN_PENDING';
export let LOGIN_FAILURE = 'LOGIN_FAILURE';

// REGISTER ACTIONS

export let REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export let REGISTER_PENDING = 'REGISTER_PENDING';
export let REGISTER_FAILURE = 'REGISTER_FAILURE';
