export const oil = {
  ComprehensiveOilInspection: {
    accNo: '',
    workOrderId: '',
    date: '',
    oilAppDtls: {
      applncType: '',
      manuf: '',
      modelNo: '',
      serialNo: '',
      nozzle: '',
      airFilterSize: '',
      combustionAnalysis: {
        Temp: false,
        CO2: false,
        O2: false,
        'Ex.Air': false,
        Effic: false,
        Draft: false,
        CO: false,
        Smoke: false,
      },
      oilFilter: {
        '1A30': false,
        NG3500: false,
        'K-10': false,
        check1: false,
        check2: false,
        check3: false,
        check4: false,
        check5: false,
        check6: false,
        check7: false,
        check8: false,
      },
      maintainanceCheckList: {
        check1: false,
        check2: false,
        check3: false,
        check4: false,
        check5: false,
        check6: false,
        check7: false,
        check8: false,
        check9: false,
        check10: false,
        check11: false,
        check12: false,
        check13: false,
        check14: false,
        check15: false,
        check16: false,
        check17: false,
      },
    },
    Notes: '',
    techName: '',
    signature: '',
    certNo: '',
    OilStorageDetails: {
      manuf: '',
      modelNo: '',
      serialNo: '',
      year: '',
      capacity: '',
      currentLevel: '',
      ReasonForInspection: {
        newInstallation: false,
        'service/maintenance': false,
        newCustomer: false,
        insuranceRequirement: false,
      },
      TankLocation: {
        indoor: false,
        outdoor: false,
      },
      InspectionCheckList: {
        check1: false,
        check2: false,
        check3: false,
        check4: false,
        check5: false,
        check6: false,
        check7: false,
        check8: false,
        check9: false,
      },
      TwoTankOilStorage: {
        check1: false,
        check2: false,
      },
    },
  },
};
